Pharmeasy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('autherization.urls')),
    path('medicines/', include('medicines.urls')),
    path('doctor/',include('doctor.urls')),
    
    path('devices/',include('devices.urls')),
    path('cart/',include('cart.urls')),




]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

autherization/urls.py
from django.contrib import admin
from django.urls import path,include
from autherization.views import *
urlpatterns = [

path('',index,name='index'),

path('signup/customer/', customer_signup, name='customer_signup'),
path('signup/doctor/', doctor_signup, name='Doctor_signup'),
path('login/', login_view, name='login'),

path('base/', base),
path('base3/', base3),
path('customerpanel/', customer_panel_view, name='customerpanel'),
path('doctorpanel/', doctor_panel_view, name='doctorpanel'),
path('adminrpanel/', admin_panel_view, name='adminpanel'),

path('aboutus/', aboutus, name='aboutus'),

path('admin_login/', admin_login, name="admin_login"),

path('forgot/', forgot_password, name="forgot_password"),
path('change_password/<int:id>', change_password, name="change_password"),

path('logout/', logout_view, name="logout_view"),
path('success/', add_feedback, name="add_feedback"),
path('feedback_success/', FeedBackSuccess.as_view(), name="feedback_success"),

]

cart/urls.py
from django.urls import path,include
from .views import *

urlpatterns=[

    path("add/<int:id>/", add_to_cart, name="add_to_cart"),
    path("cart_view/", cart_view, name="cart_view"),
    path('cart/remove/<int:id>/', devremove_cart_item, name='removeitem'),
    path("cart/placeprer/",OrderForm,name="orderitem"),
    path("cart/order_confirm/", order_confirm_view, name="order_confirm_view"),

    path('add-to-cart/<int:id>/', medadd_to_cart, name='med_to_cart'),
    path('cart/', med_cart_view, name='med_cart_view'), 
    # path('cart/remove-from-cart/<int:id>/', remove_cart_item, name='remove_cart_item'), 
    path("cart/medorder/",payment_view,name="medorder"),
    path("cart/payment/", order_confirm_view, name="payment"),
    path("cart/itemremove/<int:id>/", itemcart_remove, name="remove_cart_item"),
    path("order_view/", order_view, name="order_view"),    
    # path("success/",successview.as_view(), name="success"),


    

]

autherization/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
# Create your models here.



class NormalUser(AbstractUser):
    is_customer = models.BooleanField(default=False)
    is_doctor = models.BooleanField(default=False)
    image = models.ImageField(upload_to='images', null=True, blank=True)
    profile = models.TextField( null=True, blank=True)
    address=models.CharField(max_length=100, null=True, blank=True)
    name=models.CharField(max_length=100, null=True, blank=True)
    Department = models.CharField(max_length=20, null=True)  # Add department field
    Designation = models.CharField(max_length=20, null=True)


class Customer(models.Model):
    user = models.OneToOneField(NormalUser, on_delete=models.CASCADE) 
    phone = models.CharField(max_length=20)
    address=models.CharField(max_length=200)
    def __str__(self):
        return self.user.username


class Doctor(models.Model):
    user = models.OneToOneField(NormalUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=20, null=True)
    license_number = models.CharField(max_length=20, unique=True)
    Designation = models.CharField(max_length=20, null=True)
    Department = models.CharField(max_length=20, null=True)  # Add department field
    phone = models.IntegerField()
    image = models.ImageField(upload_to='images', null=True, blank=True)
    profile = models.CharField(max_length=100, null=True, blank=True)
    address = models.CharField(max_length=100, null=True, blank=True)
    is_active = models.BooleanField(default=False, null=True)
    is_available = models.BooleanField(default=True, null=True)
    has_requested= models.BooleanField(default=False)

    # def __str__(self):
    #     return self.user.username 
    def __str__(self):
        return self.name if self.name else f"Doctor {self.pk}"
# 
class Feedback(models.Model):
    user = models.ForeignKey(NormalUser, on_delete=models.CASCADE)
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def _str_(self):
        return f"Feedback from {self.user.username} at {self.created_at}"

doctor/forms.py
from django import forms
from autherization.models import *
from doctor.models import *

from django import forms
from .models import Doctor, Booking
from autherization.models import *
from doctor.models import *
# class BookingForm(forms.ModelForm):
#     doctor = forms.ModelChoiceField(queryset=Doctor.objects.all().order_by('name'))
#     date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
#     Department = forms.ChoiceField(choices=[])

#     class Meta:
#         model = Booking
#         fields = ['doctor', 'date', 'time', 'reason', 'Department']

#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields['Department'].choices = self.get_department_choices()

#     def get_department_choices(self):
#         return [(Department, Department) for Department in Doctor.objects.values_list('Department', flat=True).distinct()]


#     def get_doctor_choices(self):
#         doctors = Doctor.objects.all()
#         return [(doctor.id, doctor.name) for doctor in doctors]


# class BookingForm(forms.ModelForm):
#     # Define the doctor field as a ModelChoiceField
#     doctor = forms.ModelChoiceField(queryset=Doctor.objects.all(), required=True)
#     date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
#     time = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time'}))

#     class Meta:
#         model = Booking
#         fields = ['doctor', 'date', 'time', 'reason', 'department']

#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         # Make the doctor field read-only
#         self.fields['doctor'].widget.attrs['readonly'] = True
#         self.fields['doctor'].widget.attrs['disabled'] = True


from django import forms
from .models import Booking

from django import forms
from .models import Booking

from django import forms
from .models import Booking

class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['date', 'time', 'reason']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'}),
        }

    def clean_date(self):
        date = self.cleaned_data['date']
        if date < date.today():
            raise forms.ValidationError("Booking date cannot be in the past.")
        return date

class DoctorProfileUpdateForm(forms.ModelForm):
    email = forms.EmailField(label='Email', required=False)
    name = forms.CharField(label='Name', required=False)
    Designation = forms.CharField(max_length=20)
    Department = forms.CharField(max_length=20) 

    class Meta:
        model = Doctor
        fields = [ 'name', 'email', 'image', 'profile', 'address', 'phone', 'Designation', 'Department' ]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            
        }

    def __init__(self, *args, **kwargs):
        super(DoctorProfileUpdateForm, self).__init__(*args, **kwargs)
        if self.instance.user:
            self.initial['name'] = self.instance.user.name
            self.initial['email'] = self.instance.user.email

    def save(self, commit=True):
        doctor = super().save(commit=False)
        if commit:
            doctor.save()
        return doctor
    

autherization/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render, redirect
from .forms import *
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login
from django.contrib.auth import authenticate
from django.core.mail import send_mail
from django.utils.crypto import get_random_string

from django.contrib.auth import logout
from django.core.validators import RegexValidator
from medicines.models import *
from devices.models import *
from django.views.decorators.cache import never_cache
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from doctor.models import *
from datetime import datetime


def index(request):
    feedbacks = Feedback.objects.all()[:4]
    current_date = datetime.now().date()
    medicines = Medicine_inventory.objects.filter(expiry_date__gte=current_date)[:6]
    devices = DeviceInformation.objects.all()[:4]
    return render(request, "autherization/index.html", {'feedbacks': feedbacks, 'medicines': medicines, 'devices':devices})


def customer_signup(request):
    if request.method == 'POST':
        form = CustomerSignUpForm(request.POST)
        if form.is_valid():
            em = request.POST.get('email')
            form.save()
            subject = "Welcome to PharmEasy!"
            message = (
                f"Dear Customer,\n\n"
                "Thank you for creating an account with PharmEasy! "
                "We're thrilled to have you on board.\n\n"
                "Feel free to explore our website and discover a world of exciting products and services tailored just for you.\n\n"
                "If you have any questions or need assistance, don't hesitate to reach out to us.\n\n"
                "Best regards,\n"
                "The PharmEasy Team"
            )
            email_from = "pharmeasy305@gmail.com"
            email_to = em
            send_mail(subject, message, email_from, [email_to])
            return redirect('login')
    else:
        form = CustomerSignUpForm()
    return render(request, 'autherization/customersignup.html', {'form': form})

def doctor_signup(request):
    if request.method == 'POST':
        form = DoctorSignUpForm(request.POST, request.FILES)
        if form.is_valid():
            em = request.POST.get('email')
            form.save()
            subject = "Welcome to PharmEasy!"
            message = (
                f"Dear Customer,\n\n"
                "Thank you for creating an account with PharmEasy! "
                "We're thrilled to have you on board.\n\n"
                "Feel free to explore our website and discover a world of exciting products and services tailored just for you.\n\n"
                "If you have any questions or need assistance, don't hesitate to reach out to us.\n\n"
                "Best regards,\n"
                "The PharmEasy Team"
            )
            email_from = "pharmeasy305@gmail.com"
            email_to = em
            send_mail(subject, message, email_from, [email_to])
            return redirect('login')
    else:
        form = DoctorSignUpForm()
    return render(request, 'autherization/Doctorsignup.html', {'form': form})

def base(request):
    return render(request, "base.html")

def base3(request):
    return render(request, "base3.html")




# def login_view(request):
#     if request.method == 'POST':
#         form = AuthenticationForm(request, data=request.POST)
#         if form.is_valid():
#             user = form.get_user()
#             login(request, user)
            
#             if user.is_doctor:  
#                 return redirect('doctorpanel')  
#             elif user.is_customer:
#                 return redirect('customerpanel') 
            
#             else:
                
#                 return redirect('index')
            
#         # return redirect('index')
#         else:
            
#             messages.error(request, 'Invalid username or password. Please try again.')
#             return redirect('login')  
#     else:

#         form = AuthenticationForm()
#     return render(request, 'autherization/login.html', {'form': form})









from django.contrib.auth import login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.shortcuts import redirect, render

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            
            if user.is_doctor:
                return redirect('doctorpanel')  
            elif user.is_customer:
                return redirect('customerpanel') 
            else:
                return redirect('index')
        else:
            messages.error(request, 'Invalid username or password. Please try again.')
            return redirect('autherization:login_view')  
    else:
        form = AuthenticationForm()
    return render(request, 'autherization/login.html', {'form': form})


@login_required(login_url='/login/')
@never_cache
def customer_panel_view(request):
    feedbacks = Feedback.objects.all()[:4]
    current_date = datetime.now().date()
    medicines = Medicine_inventory.objects.filter(expiry_date__gte=current_date)[:6]
    devices = DeviceInformation.objects.all()[:4]

    return render(request, "autherization/customer_panel.html", {'feedbacks': feedbacks, 'medicines': medicines, 'devices':devices})


def add_feedback(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            comment = form.cleaned_data['comment']
            user = request.user
            feedback = Feedback.objects.create(user=user, comment=comment)
            feedback.save()
            return redirect('feedback_success') 
            # return HttpResponse("success")
    else:
        form = FeedbackForm()

    return render(request, 'autherization/add_feedback.html',{'form':form})


class FeedBackSuccess(TemplateView):
    template_name = "autherization/feedback_success.html"


def doctor_panel_view(request):
    doctor = request.user.doctor
    bookings = Booking.objects.filter(is_confirmed = True , doctor = doctor).order_by("time"and"date")
    return render(request, 'autherization/doctor_panel.html', {'bookings': bookings})



def admin_login(request):
    if request.method == "POST":
        a = AdminForm(request.POST)
        if a.is_valid():
            unm = a.cleaned_data['username']
            ps = a.cleaned_data['password']
            user = authenticate(request, username=unm, password=ps)
            if user is not None:

                return redirect("adminpanel")
            else: 
                return HttpResponse("login failed!")
    return render(request, "autherization/adminlogin.html")

def admin_panel_view(request):
    return render(request, "autherization/adminpanel.html")


def forgot_password(request):
    user_list = NormalUser.objects.all()
    if request.method == 'POST':
        email = request.POST.get('email')
        username = request.POST.get('username')
        
       
        for user in user_list:
            if user.email == email and user.username == username:
                user_id = user.id
                otp = get_random_string(length=6, allowed_chars='1234567890')
                print(f"Generated OTP: {otp}")
                request.session['otp'] = otp
                subject = "Password reset"
                message = f"Hi {username},\n\nSomeone has requested a new password for the following account on PharmEasy.\nIf you didn't make this request, please ignore this email.\nTo reset your password, please use the following OTP (One-Time Password): {otp} .\n\nThanks for using PharmEasy."
                email_from = "pharmeasy305@gmail.com"
                email_to = email
                send_mail(subject, message, email_from, [email_to])
                return redirect('change_password', user_id)
        else:
            return HttpResponse("Oops somthing went wrong !")
    return render(request, "autherization/forgot_password.html")



def change_password(request, id):
    user = NormalUser.objects.get(id=id)
    if request.method == "POST":
        otp = request.POST.get('otp')
        print(f"Submitted OTP: {otp}")
        if otp == request.session['otp']:
            password1 = request.POST.get('password1')
            password2 = request.POST.get('password2')
            if password1 == password2:
                user.set_password(password1)
                user.save()
                return redirect("login")
            else:
                msg = 'Sorry something went wrong!'
                return render(request, 'autherization/success.html', {'msg': msg})
        else:
            msg = "otp doesn't match!"
            return render(request, 'autherization/success.html', {'msg': msg})   
    return render(request, "autherization/change_password.html")

def logout_view(request):
    logout(request)
    return redirect(login_view)

def aboutus(request):
    return render(request, "autherization/about.html")

templates/autherization/Doctorsignup.html
{% extends "base.html" %}

{% block content %}
<style>
    #myForm{
        margin-top: 30px;
        margin-bottom: 30px;
        width: 60%;
        background-color: aliceblue;
        border: 2px ridge lightblue;
    }
    .register-form-label {
        font-weight: bold;
        color: black;
        background-color: transparent;
      
        text-align: right;
        margin-bottom: 15px;
    }
    
    .register-form-control {
        
        border-radius: 5px;
        padding: 8px;
        width: 100%;
        animation: light-travel 2s infinite;
    }
    .form-group{
        margin-left: 30px;
        margin-right: 30px;
    }
    h1{
        color: whitesmoke;
    }
    </style>
    
    <div class="mt-5"></div>
    {% if messages %}
    <div class="container d-flex justify-content-center">
        <div class="w-50" style="height: 100px;">
            <div>
                {% for m in messages %}
                    {% if m.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <strong>{{ request.user }}!</strong> {{ m }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endif %}



<div class="container mt-5 mb-5">
    <center>
    <h1>Doctor Sign Up</h1>
</center>
    <div class="d-flex justify-content-center">
            <form id="myForm" method="post" enctype="multipart/form-data" class="w-75">
                {% csrf_token %}
                {% if form.errors %}
                    <ul style="color: red;">
                        {% for field in form %}
                            {% for error in field.errors %}
                            {% if field.name == 'username' or field.name == 'email' or field.name == 'password1' or field.name == 'password2' or field.name == 'phone' %}                                    <li>{{ error }}</li>
                                {% endif %}
                            {% endfor %}
                        {% endfor %}
                    </ul>
                {% endif %}
                    <div class="form-group row mt-5">
                        <label for="id_username" class="col-sm-3 col-form-label register-form-label">{{ form.username.label_tag }}</label>
                        <div class="col-sm-9">
                            {{ form.username }}
                            <div id="usernameError" style="color: red;"></div>

                        </div>
                    </div>
                    
                    <div class="form-group row">
                        <label for="id_email" class="col-sm-3 col-form-label register-form-label">{{ form.email.label_tag }}</label>
                        <div class="col-sm-9">
                            {{ form.email }}
                            <div id="emailError" style="color: red;"></div>

                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_address" class="col-sm-3 col-form-label register-form-label">{{ form.address.label_tag }}</label>
                        <div class="col-sm-9">
                            {{ form.address }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_phone" class="col-sm-3 col-form-label register-form-label">{{ form.phone.label_tag }}</label>
                        <div class="col-sm-9">
                            {{ form.phone }}
                            <div id="phoneError" style="color: red;"></div>

                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_license_number" class="col-sm-3 col-form-label register-form-label">{{ form.license_number.label_tag }}</label>
                        <div class="col-sm-9">
                            {{ form.license_number }}
                            <!-- <div id="license_numberError" style="color: red;"></div> -->
                            {% if form.license_number.errors %}
                             <div style="color: red;">{{ form.license_number.errors }}</div>  <!-- Display license_number error message here -->
                            {% endif %}

                        </div>
                    </div>
                    
                    <div class="form-group row">
                        <label for="id_Department" class="col-sm-3 col-form-label register-form-label">{{ form.Department.label_tag}}</label>
                        <div class="col-sm-9">
                            {{ form.Department }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_Designation" class="col-sm-3 col-form-label register-form-label">{{ form.Designation.label_tag}}</label>
                        <div class="col-sm-9">
                            {{ form.Designation }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_name" class="col-sm-3 col-form-label register-form-label">{{ form.name.label_tag}}</label>
                        <div class="col-sm-9">
                            {{ form.name }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_image" class="col-sm-3 col-form-label register-form-label">{{ form.image.label_tag }}</label>
                        <div class="col-sm-9">
                            {{ form.image }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_profile" class="col-sm-3 col-form-label register-form-label">{{ form.profile.label_tag }}</label>
                        <div class="col-sm-9">
                            {{ form.profile }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_password1" class="col-sm-3 col-form-label register-form-label">{{ form.password1.label_tag }}</label>
                        <div class="col-sm-9">
                            {{ form.password1 }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_password2" class="col-sm-3 col-form-label register-form-label">{{ form.password2.label_tag }}</label>
                        <div class="col-sm-9">
                            {{ form.password2 }}
                            <div id="passwordError" style="color: red;"></div>

                        </div>
                    </div>
                    <div class="text-center mb-5">
                        <button type="submit" class="btn btn-primary">Sign Up</button>
                    </div>
                </form>
            </div>
        </div>
   
    <script>
        const form = document.getElementById('myForm');
        const usernameField = document.getElementById('id_username');
        const emailField = document.getElementById('id_email');
        const passwordField = document.getElementById('id_password1');
        const confirmPasswordField = document.getElementById('id_password2');
        const phoneField = document.getElementById('id_phone');
        const usernameError = document.getElementById('usernameError');
        const emailError = document.getElementById('emailError');
        const passwordError = document.getElementById('passwordError');
        const phoneError = document.getElementById('phoneError');
    
        usernameField.addEventListener('input', validateUsername);
        emailField.addEventListener('input', validateEmail);
        passwordField.addEventListener('input', validatePassword);
        phoneField.addEventListener('input', validatePhone);
    
        function validateUsername() {
            const username = usernameField.value;
            if (username.length < 5) {
                usernameError.textContent = 'Username must be at least 5 characters long';
            } else {
                usernameError.textContent = '';
            }
        }
    
        function validateEmail() {
            const email = emailField.value;
            const pattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
            if (!pattern.test(email)) {
                emailError.textContent = 'Invalid email address';
            } else {
                emailError.textContent = '';
            }
        }
    
        function validatePassword() {
            const password = passwordField.value;
            if (password.length < 8) {
                passwordError.textContent = 'Password must be at least 8 characters long';
            } else {
                passwordError.textContent = '';
            }
        }
    
        function validatePhone() {
            const phone = phoneField.value;
            const pattern = /^\d{10}$/;
            if (!pattern.test(phone)) {
                phoneError.textContent = 'Phone number must be 10 digits';
            } else {
                phoneError.textContent = '';
            }
        }
    </script>
    
    {%endblock%}

templates/autherization/add_feedback.html
{% extends 'base3.html' %}
{% block content %}
<style>
    .Feedback {
        max-width: 500px;
        margin: 50px auto; 
        padding: 20px;
        background-color: aliceblue;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        border-radius: 10px;
    }

    .Feedback h1 {
        margin-bottom: 30px;
        text-align: center;
        color: #333;
    }

    .Feedback form {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .Feedback form textarea {
        width: 100%;
        height: 200px;
        margin-bottom: 50px;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        resize: vertical;
    }

    .Feedback form button {
        padding: 10px 20px;
        background-color:#51eaea ;
        border-color: #51eaea;
        color: black;
        /* border: none; */
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    .Feedback form button:hover {
        background: transparent;
        color: #51eaea;
        border-color: #51eaea;
    }
</style>

<div class="Feedback">
    <h1>Add Feedback</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

templates/autherization/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>

  <style>
   
    #row{
      margin-top: 50px;
      
      
    }
    #exampleInputEmail1, #exampleInputUsername{
      width:100%
    }
    #h1{
      margin-top: 50px;
      margin-bottom: 30px;
    }
    .btn.btn-primary{
            background-color:#51eaea ;
            border-color: #51eaea;
            color: black;
            
        }

   .btn.btn-primary:hover {
    background: transparent;
    color: #51eaea;
    border-color: #51eaea;
   }
  </style>
   <meta charset="UTF-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>forgot password</title>
</head>
<body style="background-color: aliceblue;">
<div class="container">
  <div class="row" id="row">
    <div class="col-3"></div>
    <div class="col-6">
      <center>
      <h1 id="h1">Change password</h1>
    </center>
<form method="post">
  {% csrf_token %}
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Enter otp</label>
    <input type="password" name="otp" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
  </div>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Enter new password</label>
    <input type="password" name="password1" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
  </div>
  <div class="mb-3">
    <label for="exampleInputUsername" class="form-label">Re-enter password</label>
    <input type="password" name="password2" class="form-control" id="exampleInputUsername">
  </div>
  <center>
  <button type="submit" class="btn btn-primary">Submit</button>
</center>
  
</form>
    </div>
    <div class="col-3"></div>
  </div>
</div>


</body>
</html>

templates/autherization/doctor_panel.html
{% extends 'doctorbase.html' %}

{% block content %}
<style>
    h1 {
        margin-top: 30px;
    }
    .table {
        background-color: aliceblue;
        margin-top: 50px;
        margin-bottom: 50px;
    }
</style>
<div class="container">
    <center>
        <h1>Patient List</h1>
    </center>
    {% if bookings %}
        <table align="center" class="table table-hover" style="width: 80%;">
            <thead>
                <tr class="table-active">
                    <th scope="col">User Name</th>
                    <th scope="col">Date Selected</th>
                    <th scope="col">Time</th>
                    <th scope="col">Status</th>
                </tr>
            </thead>
            <tbody>
                {% for booking in bookings %}
                    <tr>
                        <td>{{ booking.patient.username }}</td>
                        <td>{{ booking.date }}</td>
                        <td>{{ booking.time }}</td>
                        <td><a href="{% url 'change_status' booking.id %}">visited</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Empty list.</p>
    {% endif %}
</div>
{% endblock %}